package redhat.policyvalidationrules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Medicine implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Color")
   private java.lang.String color;
   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;

   public Medicine()
   {
   }

   public java.lang.String getColor()
   {
      return this.color;
   }

   public void setColor(java.lang.String color)
   {
      this.color = color;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Medicine(java.lang.String color, java.lang.String name)
   {
      this.color = color;
      this.name = name;
   }

}