package redhat.policyvalidationrules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RapidRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RapidRequest() {
    }

}