package redhat.policyvalidationrules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RapidRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Age")
   private java.lang.Integer age;
   @org.kie.api.definition.type.Label(value = "Face Amount")
   private java.lang.Long faceAmount;
   @org.kie.api.definition.type.Label(value = "Result")
   private java.lang.String result;
   @org.kie.api.definition.type.Label(value = "Medicines")
   private java.util.List<redhat.policyvalidationrules.model.Medicine> meds;
   @org.kie.api.definition.type.Label(value = "Travels")
   private java.util.List<redhat.policyvalidationrules.model.Travel> travels;

   public RapidRequest()
   {
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.Long getFaceAmount()
   {
      return this.faceAmount;
   }

   public void setFaceAmount(java.lang.Long faceAmount)
   {
      this.faceAmount = faceAmount;
   }

   public java.lang.String getResult()
   {
      return this.result;
   }

   public void setResult(java.lang.String result)
   {
      this.result = result;
   }

   public java.util.List<redhat.policyvalidationrules.model.Medicine> getMeds()
   {
      return this.meds;
   }

   public void setMeds(
         java.util.List<redhat.policyvalidationrules.model.Medicine> meds)
   {
      this.meds = meds;
   }

   public java.util.List<redhat.policyvalidationrules.model.Travel> getTravels()
   {
      return this.travels;
   }

   public void setTravels(
         java.util.List<redhat.policyvalidationrules.model.Travel> travels)
   {
      this.travels = travels;
   }

   public RapidRequest(java.lang.Integer age, java.lang.Long faceAmount,
         java.lang.String result,
         java.util.List<redhat.policyvalidationrules.model.Medicine> meds,
         java.util.List<redhat.policyvalidationrules.model.Travel> travels)
   {
      this.age = age;
      this.faceAmount = faceAmount;
      this.result = result;
      this.meds = meds;
      this.travels = travels;
   }

}