package redhat.policyvalidationrules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Travel implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Travel Country Code")
   private java.lang.String travelCountryCode;
   @org.kie.api.definition.type.Label(value = "Travel Days")
   private java.lang.Integer travelDays;

   public Travel()
   {
   }

   public java.lang.String getTravelCountryCode()
   {
      return this.travelCountryCode;
   }

   public void setTravelCountryCode(java.lang.String travelCountryCode)
   {
      this.travelCountryCode = travelCountryCode;
   }

   public java.lang.Integer getTravelDays()
   {
      return this.travelDays;
   }

   public void setTravelDays(java.lang.Integer travelDays)
   {
      this.travelDays = travelDays;
   }

   public Travel(java.lang.String travelCountryCode,
         java.lang.Integer travelDays)
   {
      this.travelCountryCode = travelCountryCode;
      this.travelDays = travelDays;
   }

}